"""empty message

Revision ID: bbc1430a988f
Revises: 
Create Date: 2024-09-20 10:09:46.834802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc1430a988f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcacao',
    sa.Column('id_hr', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.DateTime(timezone=50), nullable=False),
    sa.Column('dia', sa.String(length=50), nullable=False),
    sa.Column('mes', sa.String(length=50), nullable=False),
    sa.Column('ano', sa.String(length=50), nullable=False),
    sa.Column('hora', sa.String(length=50), nullable=False),
    sa.Column('st', sa.String(length=2), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_hr')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_usuario', sa.String(length=50), nullable=False),
    sa.Column('login_usuario', sa.String(length=20), nullable=False),
    sa.Column('senha_usuario', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('login_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('marcacao')
    # ### end Alembic commands ###
